remotes::install_github("sizespectrum/mizerExperimental")
library(dplyr)
library(waldo)
library(mizerExperimental)
source("components.R")
source("helpers.R")
source("plots.R")
source("rhoControl.R")
source("rates.R")
params <- readRDS("params.rds")
catch <- readRDS("catch.rds")