remotes::install_github("sizespectrum/mizerExperimental", ref = "tuneMR")
library(dplyr)
library(waldo)
library(mizerExperimental)
source("R/components.R")
source("R/helpers.R")
source("R/plots.R")
source("R/rhoControl.R")
source("R/rates.R")
source("R/steady.R")
load("data/params.rda")
load("data/catch.rda")
